[package]
name = "logisim-desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
logisim-common = { path = "../common" }
winit = { version = "0.29.4", features = ["rwh_05"] }
pollster = "0.3.0"
env_logger = "0.10.1"
log = "0.4"
clipboard = "0.5.0"
fontdue = "0.8.0"
