[package]
name = "logisim-desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
logisim-common = { path = "../common" }
winit = { version = "0.29.4", features = ["rwh_05"] }
pollster = "0.3"
env_logger = "0.10"
log = "0.4"
clipboard = "0.5"
fontdue = "0.8"
bincode = "1.3"
directories = "5.0"
